// Mocks generated by Mockito 5.3.2 from annotations
// in iso_net/test/Service/mock_provider.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:iso_net/helper_manager/network_manager/api_const.dart' as _i6;
import 'package:iso_net/helper_manager/network_manager/remote_service.dart'
    as _i4;
import 'package:iso_net/model/response_model/responese_datamodel.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseModel_1<T> extends _i1.SmartFake
    implements _i3.ResponseModel<T> {
  _FakeResponseModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteServices extends _i1.Mock implements _i4.RemoteServices {
  MockRemoteServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
  @override
  set dio(_i2.Dio? _dio) => super.noSuchMethod(
        Invocation.setter(
          #dio,
          _dio,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<_i3.ResponseModel<T>> createGetRequest<T>({
    required _i6.ApiType? typeOfEndPoint,
    Map<String, dynamic>? params,
    String? urlParam,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGetRequest,
          [],
          {
            #typeOfEndPoint: typeOfEndPoint,
            #params: params,
            #urlParam: urlParam,
          },
        ),
        returnValue:
            _i5.Future<_i3.ResponseModel<T>>.value(_FakeResponseModel_1<T>(
          this,
          Invocation.method(
            #createGetRequest,
            [],
            {
              #typeOfEndPoint: typeOfEndPoint,
              #params: params,
              #urlParam: urlParam,
            },
          ),
        )),
      ) as _i5.Future<_i3.ResponseModel<T>>);
  @override
  _i5.Future<_i3.ResponseModel<T>> createTestGetRequest<T>({
    required _i6.ApiType? typeOfEndPoint,
    Map<String, dynamic>? params,
    String? urlParam,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTestGetRequest,
          [],
          {
            #typeOfEndPoint: typeOfEndPoint,
            #params: params,
            #urlParam: urlParam,
          },
        ),
        returnValue:
            _i5.Future<_i3.ResponseModel<T>>.value(_FakeResponseModel_1<T>(
          this,
          Invocation.method(
            #createTestGetRequest,
            [],
            {
              #typeOfEndPoint: typeOfEndPoint,
              #params: params,
              #urlParam: urlParam,
            },
          ),
        )),
      ) as _i5.Future<_i3.ResponseModel<T>>);
  @override
  _i5.Future<_i3.ResponseModel<T>> createPostRequest<T>({
    required _i6.ApiType? typeOfEndPoint,
    Map<String, dynamic>? params,
    String? urlParam,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPostRequest,
          [],
          {
            #typeOfEndPoint: typeOfEndPoint,
            #params: params,
            #urlParam: urlParam,
          },
        ),
        returnValue:
            _i5.Future<_i3.ResponseModel<T>>.value(_FakeResponseModel_1<T>(
          this,
          Invocation.method(
            #createPostRequest,
            [],
            {
              #typeOfEndPoint: typeOfEndPoint,
              #params: params,
              #urlParam: urlParam,
            },
          ),
        )),
      ) as _i5.Future<_i3.ResponseModel<T>>);
  @override
  _i5.Future<_i3.ResponseModel<T>> createTestPostRequest<T>({
    required _i6.ApiType? typeOfEndPoint,
    Map<String, dynamic>? params,
    String? urlParam,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTestPostRequest,
          [],
          {
            #typeOfEndPoint: typeOfEndPoint,
            #params: params,
            #urlParam: urlParam,
          },
        ),
        returnValue:
            _i5.Future<_i3.ResponseModel<T>>.value(_FakeResponseModel_1<T>(
          this,
          Invocation.method(
            #createTestPostRequest,
            [],
            {
              #typeOfEndPoint: typeOfEndPoint,
              #params: params,
              #urlParam: urlParam,
            },
          ),
        )),
      ) as _i5.Future<_i3.ResponseModel<T>>);
  @override
  _i5.Future<_i3.ResponseModel<T>> createPutRequest<T>({
    required _i6.ApiType? typeOfEndPoint,
    Map<String, dynamic>? params,
    String? urlParam,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPutRequest,
          [],
          {
            #typeOfEndPoint: typeOfEndPoint,
            #params: params,
            #urlParam: urlParam,
          },
        ),
        returnValue:
            _i5.Future<_i3.ResponseModel<T>>.value(_FakeResponseModel_1<T>(
          this,
          Invocation.method(
            #createPutRequest,
            [],
            {
              #typeOfEndPoint: typeOfEndPoint,
              #params: params,
              #urlParam: urlParam,
            },
          ),
        )),
      ) as _i5.Future<_i3.ResponseModel<T>>);
  @override
  _i5.Future<_i3.ResponseModel<T>> createDeleteRequest<T>({
    required _i6.ApiType? typeOfEndPoint,
    Map<String, dynamic>? params,
    String? urlParam,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDeleteRequest,
          [],
          {
            #typeOfEndPoint: typeOfEndPoint,
            #params: params,
            #urlParam: urlParam,
          },
        ),
        returnValue:
            _i5.Future<_i3.ResponseModel<T>>.value(_FakeResponseModel_1<T>(
          this,
          Invocation.method(
            #createDeleteRequest,
            [],
            {
              #typeOfEndPoint: typeOfEndPoint,
              #params: params,
              #urlParam: urlParam,
            },
          ),
        )),
      ) as _i5.Future<_i3.ResponseModel<T>>);
  @override
  _i3.ResponseModel<T> createErrorResponse<T>({
    required int? status,
    required String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createErrorResponse,
          [],
          {
            #status: status,
            #message: message,
          },
        ),
        returnValue: _FakeResponseModel_1<T>(
          this,
          Invocation.method(
            #createErrorResponse,
            [],
            {
              #status: status,
              #message: message,
            },
          ),
        ),
      ) as _i3.ResponseModel<T>);
  @override
  _i5.Future<_i3.ResponseModel<T>> uploadRequest<T>(
    _i6.ApiType? apiType, {
    Map<String, dynamic>? params,
    List<_i6.AppMultiPartFile>? arrFile,
    String? urlParam,
    dynamic Function(double)? onFileUpload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadRequest,
          [apiType],
          {
            #params: params,
            #arrFile: arrFile,
            #urlParam: urlParam,
            #onFileUpload: onFileUpload,
          },
        ),
        returnValue:
            _i5.Future<_i3.ResponseModel<T>>.value(_FakeResponseModel_1<T>(
          this,
          Invocation.method(
            #uploadRequest,
            [apiType],
            {
              #params: params,
              #arrFile: arrFile,
              #urlParam: urlParam,
              #onFileUpload: onFileUpload,
            },
          ),
        )),
      ) as _i5.Future<_i3.ResponseModel<T>>);
}
